apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-code
spec:
 replicas: 3
 template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: nginx-index
          readOnly: true

      volumes:
      - name: nginx-index
        configMap:
          name: nginx-conf
          items: 
            - key: nginx.index
              path: index.html  